### ISSUE TITLE
EPUB/MOBI: Ordered list styling

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/pressbooks-clarke#10]
### Description

On EPUB and MOBI, Ordered lists do not seem to have correct styling:
EPUB before:
![screen shot 2018-05-15 at 1 20 03 pm](https://user-images.githubusercontent.com/21149722/40077470-bdb3dc02-584f-11e8-81d7-27b47fa1fec2.png)
EPUB after: 
![screen shot 2018-05-15 at 1 19 52 pm](https://user-images.githubusercontent.com/21149722/40077480-c952b7ea-584f-11e8-8c87-fa7dbe4b1284.png)

MOBI before:
![screen shot 2018-05-15 at 2 10 21 pm](https://user-images.githubusercontent.com/21149722/40077543-f1cea10c-584f-11e8-9f62-2ed831716b8b.png)
MOBI After:
![screen shot 2018-05-15 at 2 10 33 pm](https://user-images.githubusercontent.com/21149722/40077554-f9aff358-584f-11e8-9ddd-107633bafc73.png)

**Comment by greatislander** [comment]
Deliberate change.
