### ISSUE TITLE
PDF: Edu-textbox styling issues

### ISSUE THREAD

**Issue by dannylonglegs** [pressbooks/pressbooks-clarke#4]
### Prerequisites

_Check the boxes below by changing them from `[ ]` to `[x]`._

* [x ] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [x ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [Pressbooks Book](http://github.com/pressbooks/pressbooks-book/releases/latest/), the latest version of [this book theme](http://github.com/pressbooks/pressbooks-clarke/releases/latest/) and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [x ] Are you experiencing the issue while using this book theme?
* [x ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-clarke) to see if your bug or enhancement is already listed?

### Description

- [x] Square edu-textbox on 'Before', border radius on 'After', which is correct?
- [ ] Edu-textbox list styling issues. Images below:
Before:
![screen shot 2018-05-10 at 2 21 14 pm](https://user-images.githubusercontent.com/21149722/39888130-f3dfae10-5461-11e8-9084-c799f8babb89.png)
After:
![screen shot 2018-05-10 at 2 21 24 pm](https://user-images.githubusercontent.com/21149722/39888225-34a12712-5462-11e8-82f5-634d04db1545.png)

**Comment by greatislander** [comment]
Lists will be addressed in pressbooks/buckram#126.
