### ISSUE TITLE
Chapter number alignment in table of contents gets disrupted with double digit numbers

### ISSUE THREAD

**Issue by mcgratay** [pressbooks/pressbooks-clarke#45]
### Description

When the body font size is raised in the PDF Theme Options, the formatting and alignment of chapter numbers in the table of contents is overridden. This seems to especially affect double digit numbered chapters (10+). 
![Screen Shot 2019-04-23 at 4 29 56 PM](https://user-images.githubusercontent.com/39064028/56613647-0eb26800-65e5-11e9-901f-1bbe0c95904e.png)
Example test book: https://tocnumberingerror.textopress.com

### Steps to Reproduce

1. Access an existing test book or create a new one
2. Go to **Appearance** to select the Clarke theme
3. Create at least ten chapters with titles 
4. Go to **Appearance > Theme Options** and select **PDF Options**, then raise the body font size to 13 and save changes
5. Go to **Export** and export a PDF file 
6. View table of contents 

**Expected behavior:** Double-digit chapter numbers align left with single-digit chapter numbers. 

**Actual behavior:** Double-digit chapter numbers are misaligned when body font size is changed.

**Comment by SteelWagstaff** [comment]
@mcgratay will you check to see if this issue still persists after TOC fixes from this summer?

**Comment by mcgratay** [comment]
Resolved
