### ISSUE TITLE
Tables don't inherit expected styles in PDF exports

### ISSUE THREAD

**Issue by SteelWagstaff** [pressbooks/pressbooks-clarke#49]
### Description

Tables don't look the way users expect them to in the PDF exports. In particular, Clarke does not produce full grid borders, or shaded cells/rows/columns, etc., even when these are explicitly set in the table class. See also https://github.com/pressbooks/pressbooks-book/issues/336

### Steps to Reproduce

1. Create a table using the WYSIWYG table editor. 
2. Set the table to full-grid from the table properties option
3. Change one of the table rows to 'shaded' from the row properties option
4. Export this chapter in a PDF using the Clarke theme.

**Expected behavior:** [What you expected to happen]
The table in the PDF would have full grid border lines and a shaded row.

**Actual behavior:** [What actually happened]
The table does not include border lines for cells or shaded rows. 

See two sample files produced by the same underlying book:
[MJCSL Table Test McLuhan (2).pdf](https://github.com/pressbooks/pressbooks-clarke/files/3617954/MJCSL.Table.Test.McLuhan.2.pdf) This PDF uses the McLuhan theme. Tables do have full grid lines and shaded rows. 
[MJCSL Table Test Clarke (2).pdf](https://github.com/pressbooks/pressbooks-clarke/files/3617953/MJCSL.Table.Test.Clarke.2.pdf). This PDF uses Clarke. Tables do not have full grid border lines or shaded rows.

**Comment by SteelWagstaff** [comment]
Add'l note: I'm unsure at this time whether this issue is specific to Clarke or also appears in other older themes.

**Comment by SteelWagstaff** [comment]
I've tested on a few more themes. Similar issues appear for tables created in Jacobs (see [Table-Test_Jacobs.pdf](https://github.com/pressbooks/pressbooks-clarke/files/3623616/Table-Test_Jacobs.pdf)) and to a lesser extent in Adunis (see
[Table-Test_Adunis.pdf](https://github.com/pressbooks/pressbooks-clarke/files/3623615/Table-Test_Adunis.pdf)). Tables export as expected in both McLuhan and Leonard. Will test on more themes when able.

**Comment by mcgratay** [comment]
[tablelinecss.txt](https://github.com/pressbooks/pressbooks-clarke/files/3752420/tablelinecss.txt)

^ 3 sets of CSS for full grid tables (PDF, webbook, ebook)

**Comment by mcgratay** [comment]
resolved ✅
